"""
tools/github_pusher.py
───────────────────────
Creates a GitHub repository and pushes all generated files to it.

Authentication
  Uses a GitHub Personal Access Token (classic) stored in GITHUB_TOKEN env var.
  Token needs: repo scope (full control of private repositories).

Steps
  1. POST /user/repos                       → create repo
  2. For each file: PUT /repos/{owner}/{repo}/contents/{path}  → upload
  3. Return the repo URL on success.

Why no git CLI?
  The PyGithub library speaks the GitHub REST API directly — no git binary
  required, no SSH key setup.  This makes it self-contained and Colab-friendly.
"""

import os
import base64
from pathlib import Path
from typing import Optional

try:
    from github import Github, GithubException
    PYGITHUB_AVAILABLE = True
except ImportError:
    PYGITHUB_AVAILABLE = False


def push_to_github(
    files: dict[str, str],
    repo_name: str = "devsquad-output",
    description: str = "Generated by DevSquad autonomous engineering team",
    private: bool = False,
) -> dict[str, str]:
    """
    Create a GitHub repo and push all files to it.

    Parameters
    ----------
    files       : mapping of {relative_path: file_content_string}
    repo_name   : name for the new GitHub repository
    description : repo description shown on GitHub
    private     : whether to make the repo private

    Returns
    -------
    dict with keys:
      "status"   : "success" or "error"
      "repo_url" : HTML URL of the created repo (on success)
      "message"  : human-readable status message
    """
    if not PYGITHUB_AVAILABLE:
        return {
            "status": "error",
            "repo_url": "",
            "message": "PyGithub not installed. Run: pip install PyGithub",
        }

    token = os.environ.get("GITHUB_TOKEN", "")
    if not token:
        return {
            "status": "error",
            "repo_url": "",
            "message": (
                "GITHUB_TOKEN is not set. "
                "Add it to your .env file to enable GitHub push."
            ),
        }

    try:
        g = Github(token)
        user = g.get_user()

        # Create repository — handle name collision gracefully
        try:
            repo = user.create_repo(
                name=repo_name,
                description=description,
                private=private,
                auto_init=True,   # creates main branch with empty README
            )
        except GithubException as e:
            if e.status == 422:  # repo already exists
                repo = user.get_repo(repo_name)
            else:
                raise

        # Push each file via the Contents API
        pushed = []
        for filepath, content in files.items():
            encoded = base64.b64encode(content.encode("utf-8")).decode("utf-8")
            try:
                # Try to update existing file first
                existing = repo.get_contents(filepath)
                repo.update_file(
                    path=filepath,
                    message=f"DevSquad: update {filepath}",
                    content=content,
                    sha=existing.sha,
                )
            except GithubException:
                # File doesn't exist yet — create it
                repo.create_file(
                    path=filepath,
                    message=f"DevSquad: add {filepath}",
                    content=content,
                )
            pushed.append(filepath)

        return {
            "status": "success",
            "repo_url": repo.html_url,
            "message": (
                f"Pushed {len(pushed)} files to {repo.html_url}\n"
                f"Files: {', '.join(pushed)}"
            ),
        }

    except GithubException as e:
        return {
            "status": "error",
            "repo_url": "",
            "message": f"GitHub API error {e.status}: {e.data.get('message', str(e))}",
        }
    except Exception as e:
        return {
            "status": "error",
            "repo_url": "",
            "message": f"Unexpected error: {type(e).__name__}: {e}",
        }


def extract_files_from_crew_output(raw_output: str) -> dict[str, str]:
    """
    Parse the '## File: <name>' markers from crew output into a dict.

    The Developer and QA agents use this format:
      ## File: weather.py
      ```python
      ... code ...
      ```
    This function extracts each block and returns {filename: content}.
    """
    import re

    files: dict[str, str] = {}
    # Match  ## File: <name>  followed by a fenced code block (or plain text)
    pattern = re.compile(
        r"##\s*File:\s*(\S+)\s*\n"          # ## File: filename
        r"(?:```\w*\n)?(.*?)(?:```|\Z)",     # optional fence, then content
        re.DOTALL,
    )
    for match in pattern.finditer(raw_output):
        filename = match.group(1).strip()
        content = match.group(2).strip()
        if filename and content:
            files[filename] = content

    return files
