"""
calculator_agent — Generated by AlgoProfessor Agent Creator
Performs arithmetic calculations from natural language input using GPT-4o.
"""

import os
import openai
from fastapi import FastAPI
from pydantic import BaseModel

app = FastAPI(title="Calculator Agent")
client = openai.OpenAI(api_key=os.environ.get("OPENAI_API_KEY", ""))


class RunRequest(BaseModel):
    input: str


class RunResponse(BaseModel):
    output: str


@app.get("/health")
def health():
    return {"status": "ok", "agent": "calculator_agent"}


@app.post("/run", response_model=RunResponse)
def run(req: RunRequest):
    response = client.chat.completions.create(
        model="gpt-4o",
        messages=[
            {
                "role": "system",
                "content": (
                    "You are a precise calculator assistant. "
                    "Evaluate the mathematical expression or word problem the user provides. "
                    "Return only the numeric result with a brief explanation."
                ),
            },
            {"role": "user", "content": req.input},
        ],
        temperature=0,
    )
    return RunResponse(output=response.choices[0].message.content.strip())
